In [7]:
#import csv as DataFrame pandas object
import pandas as pd
df = pd.read_csv (r'C:\Users\nsarw\Downloads\Greenhouse_Gas.csv')
print(df.columns)

Index(['ObjectId2', 'Country', 'ISO2', 'ISO3', 'Indicator', 'Unit', 'Source',
       'CTS_Code', 'CTS_Name', 'CTS_Full_Descriptor', 'Industry', 'Gas_Type',
       'Scale', 'F2010', 'F2011', 'F2012', 'F2013', 'F2014', 'F2015', 'F2016',
       'F2017', 'F2018', 'F2019', 'F2020', 'F2021'],
      dtype='object')

In [21]:
df_use = df[['Country', 'Industry', 'Gas_Type', 'F2010', 'F2011','F2012', 'F2013', 'F2014', 'F2015', 'F2016', 'F2017', 'F2018', 'F2019', 'F2020', 'F2021']]
df_use.tail()

,Country,Industry,Gas_Type,F2010,F2011,F2012,F2013,F2014,F2015,F2016,F2017,F2018,F2019,F2020,F2021
1048,World,Transportation and Storage,Nitrous oxide,63.018148,64.393261,64.926048,65.861839,67.256189,67.641084,68.714743,70.909566,72.910515,75.393768,69.851800,74.303602
1049,World,"Water supply; sewerage, waste management and r...",Carbon dioxide,233.896826,231.071540,255.020810,258.297348,263.427288,271.748519,277.749986,279.746081,280.538247,283.778512,279.077068,288.848298
1050,World,"Water supply; sewerage, waste management and r...",Greenhouse gas,2749.793321,2795.280460,2868.285412,2898.376789,2945.722164,2989.711922,3031.707121,3080.858664,3125.628249,3188.183501,3045.400161,3343.656841
1051,World,"Water supply; sewerage, waste management and r...",Methane,2395.884042,2442.058042,2487.932118,2511.646109,2551.971134,2585.507218,2618.931693,2663.410964,2706.269276,2762.621585,2631.828053,2907.266047
1052,World,"Water supply; sewerage, waste management and r...",Nitrous oxide,120.012453,122.150877,125.332484,128.433332,130.323742,132.456185,135.025442,137.701619,138.820726,141.783404,134.495039,147.542495

In [17]:
df_use.groupby(["Industry","Gas_Type"], as_index=False)["F2017"].sum()

,Industry,Gas_Type,F2017
0,"Agriculture, Forestry and Fishing",Carbon dioxide,1941.394936
1,"Agriculture, Forestry and Fishing",Greenhouse gas,31128.738290
2,"Agriculture, Forestry and Fishing",Methane,18453.568675
3,"Agriculture, Forestry and Fishing",Nitrous oxide,10733.774679
4,Construction,Carbon dioxide,10638.818878
5,Construction,Greenhouse gas,14206.184100
6,Construction,Methane,3512.459663
7,Construction,Nitrous oxide,54.905559
8,"Electricity, Gas, Steam and Air Conditioning S...",Carbon dioxide,67229.450144
9,"Electricity, Gas, Steam and Air Conditioning S...",Greenhouse gas,68673.352842
10,"Electricity, Gas, Steam and Air Conditioning S...",Methane,784.596829
11,"Electricity, Gas, Steam and Air Conditioning S...",Nitrous oxide,659.305873
12,Manufacturing,Carbon dioxide,39386.463510
13,Manufacturing,Fluorinated gases,2971.646388
14,Manufacturing,Greenhouse gas,45356.111627
15,Manufacturing,Methane,1969.853947
16,Manufacturing,Nitrous oxide,1028.147782
17,Mining,Carbon dioxide,10031.335096
18,Mining,Greenhouse gas,13284.490122
19,Mining,Methane,3201.562558
20,Mining,Nitrous oxide,51.592467
21,Other Services Industries,Carbon dioxide,12448.394119
22,Other Services Industries,Fluorinated gases,262.680899
23,Other Services Industries,Greenhouse gas,14222.359669
24,Other Services Industries,Methane,1384.736079
25,Other Services Industries,Nitrous oxide,126.548571
26,Total Households,Carbon dioxide,26325.524680
27,Total Households,Fluorinated gases,90.750698
28,Total Households,Greenhouse gas,27144.861058
29,Total Households,Methane,232.432217
30,Total Households,Nitrous oxide,496.153465
31,Total Industry and Households,Carbon dioxide,185115.315538
32,Total Industry and Households,Fluorinated gases,3573.104908
33,Total Industry and Households,Greenhouse gas,245027.419051
34,Total Industry and Households,Methane,42145.700507
35,Total Industry and Households,Nitrous oxide,14193.298112
36,Transportation and Storage,Carbon dioxide,15769.257030
37,Transportation and Storage,Fluorinated gases,248.026923
38,Transportation and Storage,Greenhouse gas,16582.609147
39,Transportation and Storage,Methane,209.786874
40,Transportation and Storage,Nitrous oxide,355.538320
41,"Water supply; sewerage, waste management and r...",Carbon dioxide,1344.677150
42,"Water supply; sewerage, waste management and r...",Greenhouse gas,14428.712209
43,"Water supply; sewerage, waste management and r...",Methane,12396.703662
44,"Water supply; sewerage, waste management and r...",Nitrous oxide,687.331396

In [28]:
df_africa = df_use[df_use['Country'].isin(['Africa', 'Asia', 'Europe', 'Oceania', 'Americas'])];
df_africa

,Country,Industry,Gas_Type,F2010,F2011,F2012,F2013,F2014,F2015,F2016,F2017,F2018,F2019,F2020,F2021
45,Africa,"Agriculture, Forestry and Fishing",Carbon dioxide,5.483346,5.561609,6.161359,6.640417,7.062052,7.206354,7.880148,8.532024,8.593665,8.963838,9.367897,11.349848
46,Africa,"Agriculture, Forestry and Fishing",Greenhouse gas,691.708721,703.387895,731.427718,746.506093,760.072502,774.769282,797.774358,804.550418,820.242277,824.164009,746.012678,765.998084
47,Africa,"Agriculture, Forestry and Fishing",Methane,456.942886,464.700985,484.494127,492.668269,502.025779,511.896109,527.085026,528.405787,540.722956,543.184383,490.431554,519.403035
48,Africa,"Agriculture, Forestry and Fishing",Nitrous oxide,229.282488,233.125301,240.772231,247.197407,250.984671,255.666820,262.809184,267.612607,270.925656,272.015788,246.213227,235.245202
49,Africa,Construction,Carbon dioxide,113.268164,108.701746,109.829265,110.057495,109.998637,107.896354,107.646709,109.120900,111.219910,112.599137,106.064110,99.627619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
747,Oceania,Transportation and Storage,Nitrous oxide,1.279423,1.316398,1.312859,1.324707,1.355235,1.409743,1.434172,1.459673,1.443345,1.467905,1.339553,1.463251
748,Oceania,"Water supply; sewerage, waste management and r...",Carbon dioxide,0.139227,0.140897,0.163577,0.164712,0.410370,0.198849,0.244130,0.178537,0.180866,0.145975,0.136198,0.133954
749,Oceania,"Water supply; sewerage, waste management and r...",Greenhouse gas,20.179967,19.479467,17.982395,17.318173,18.537776,19.102457,19.929558,20.148624,20.576134,20.683368,19.456470,20.705205
750,Oceania,"Water supply; sewerage, waste management and r...",Methane,19.427433,18.708204,17.140090,16.481065,17.398026,18.121731,18.851431,19.129582,19.574380,19.702381,18.543635,19.789642
751,Oceania,"Water supply; sewerage, waste management and r...",Nitrous oxide,0.613308,0.630367,0.678727,0.672395,0.729380,0.781878,0.833997,0.840505,0.820888,0.835013,0.776637,0.781609